### ISSUE TITLE
Generated responses are occasionally in languages other than Apex

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/Einstein-GPT-for-Developers#1]
Sometimes, when I ask for a method to be created in Apex ie.

`Create a function to take two numbers and print the sum`

the generated response will be in a language other than Apex, ie. Python. If I'm working within an existing Apex file, I'd like the generated code to also be in Apex.

**Comment by jkranz-rk** [comment]
@abrantes23 strictly speaking, there is a distinction between methods and functions, but practically speaking it isn't so wrong to describe apex methods as functions. sure, Apex doesn't have _pure_ functions, but its common and correct _enough_ to refer to apex methods as functions, and I think a tool meant to convert the intent of natural human language to executable code should not care about the kind of distinction that doesn't impact how the resulting code should be composed.

By the same distinction, much of the behavior written in LWC are written as class members, which are more "correctly" described as methods

**Comment by gbockus-sf** [comment]
This issue was resolved by further training of the LLM.  Please reopen if you encounter a new prompt that generates something other then apex.
