### ISSUE TITLE
Request failed with status code 503

### ISSUE THREAD

**Issue by RogerThattt** [forcedotcom/Einstein-GPT-for-Developers#100]
Right click on the code i click on AgentForce:Generate a test

Select the Class containing the method for which youw ant to generate the test

when i chose multiple methods i am getting Request failed with status code 503

even when i chose one i am getting Request failed with status code 503

**Comment by lahernandezb** [comment]
@RogerThattt thanks for the ticket. The team is aware of this issue, has identified the problem, and is currently working on a fix. 

Have you tried making this request again since this issue was created? If so, did you have any success with the request?

**Comment by gbockus-sf** [comment]
We had a service issue last week that was resolved that same day. Please reopen if you are still seeing issues. Thanks!
