### ISSUE TITLE
Issues with dev assistant

### ISSUE THREAD

**Issue by BillyC92** [forcedotcom/Einstein-GPT-for-Developers#101]
### Summary

I am unable to get any sort of response from the Dev Assistant, other than if I say 'Hi' or 'Hello' which gives me a generic response.

### Steps To Reproduce:

1.  Go to Dev Assistant Visual Studio Extension
2. Type in 'Hello' and receive initial response.
3. Type in another prompt after this initial response, e.g. 'Explain ...'.
4. Receive error message 'Oops, something went wrong. Try rewording your request or clearing the chat.'
5. Other scenario being if I enter anything as the first message that isn't 'hello', I also receive the error.
6. Apex language server is running.

### Expected result

Should receive a response

### Actual result

Received error

### Additional information

_Feel free to attach a screenshot_.
<img width="425" alt="Screenshot 2024-10-21 at 15 00 10" src="https://github.com/user-attachments/assets/d80dbb9e-ff0f-4d7a-8408-92dbd26aa877">

**Salesforce Extension Version in VS Code**: Salesforce Extension Pack (Expanded) v62.0.0

**Salesforce Einstein For Developers Version in VS Code**: v1.2.0

**OS and version**: 14.0 (23A344)

**VS Code version**:  1.94.2 (Universal)

**Comment by theseptemberguy** [comment]
Having exactly the same issue. From VS code about,

Version: 1.94.1 (user setup)
OS: Windows_NT x64 10.0.19045

**Comment by AmbroseOodle** [comment]
Having exactly the same issue.

**Comment by lahernandezb** [comment]
@BillyC92 could you enable debug logging in your session? Re-attempt to generate a response and share the contents on the logs (can be found in the output panel or in dev console). The behavior you are seeing might be due to an already identified issue the team is working on, but I would like to confirm.

**Comment by gbockus-sf** [comment]
We had a service issue last week that was resolved that same day.  Please reopen if you are still seeing issues. Thanks!
