### ISSUE TITLE
Terms of Use link in VS Code links to blank wiki page

### ISSUE THREAD

**Issue by thedanfernandez** [forcedotcom/Einstein-GPT-for-Developers#14]
Steps to reproduce

- Enable extension and expand the popup message which should show the below text and click the link
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/8809372/57f581e7-de19-4620-a957-449b352502c0)

> We're excited that you're test driving Einstein for Developers. Make sure to read our [Terms of Use](https://github.com/forcedotcom/Einstein-GPT-for-Developers/wiki/Additional-Terms-of-Use-for-the-Einstein-GPT-for-Developers-Extensions) before you start.

## Issue
**Expected behavior**: The link takes you to the Terms of Use page
**Actual behavior**: You are redirected to a blank page as shown below as the page doesn't exist (hence the edit page warning)

![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/8809372/fadf464a-db2c-472b-a820-6c1b4ef64e43)

Extension: `salesforce.salesforcedx-einstein-gpt` 
Version: `v0.19.1`

**Comment by cromwellryan** [comment]
Thanks for reporting! We've restored the missing Terms page that was set aside in the shuffle. 

Let us know if you have any more questions.
