### ISSUE TITLE
Feedback in the panel can get out of sync with feedback in the history

### ISSUE THREAD

**Issue by jkranz-rk** [forcedotcom/Einstein-GPT-for-Developers#16]
I'm not quite sure how _exactly_ to reproduce this, but when the side panel current prompt result is listed in the history, the feedback (voted thumbs up/down) can get out of sync between the two:

https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/40637750/093829cf-95fa-4fe1-b35c-df3e80b1d29a

**Comment by jonifazo** [comment]
Hi[jkranz-rk](https://github.com/jkranz-rk)! Thank you for bringing this to our attention. Great catch!

**Comment by smarvez** [comment]
[W-14129250](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001abV4UYAU/view) filed to address this issue
