### ISSUE TITLE
SFApiRequestError: Request failed with status code 500

### ISSUE THREAD

**Issue by elliot41** [forcedotcom/Einstein-GPT-for-Developers#17]
Hi guys, 

When I try to generate code, I have this error message "SFApiRequestError: Request failed with status code 500". I have a company proxy that may block the call. Is there a way to see which url is being called ?

**Comment by elliot41** [comment]
Hi abrantes23, yes I enabled Einstein for Developers on my local VS Code, but i got this error.
Ok i'll try to use it from "Code Builder".

On my local vscode, i still have the issue event if einstein is white : 
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/15812951/0b74985a-918c-4a26-b9ff-e3255e1a4446)

**Comment by gbockus-sf** [comment]
Hello!  You can enable the debug logging via the extensions settings and then you can see the specific API endpoint we are calling from the developer tools (console). 
<img width="1248" alt="Screenshot 2023-09-14 at 5 14 08 PM" src="https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/76090802/48943c58-a3cb-4416-8c93-7cb9763c3890">

**Comment by gbockus-sf** [comment]
Closing this issue out now as it's been a couple of weeks without progress.  @elliot41 please reopen if you'd like to continue debugging the issue. Thanks!

**Comment by gbockus-sf** [comment]
@BhavsarShivam in the better late then never department please checkout my comment on https://github.com/forcedotcom/Einstein-GPT-for-Developers/issues/60.
