### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by A2152225** [forcedotcom/Einstein-GPT-for-Developers#19]
It seems the model only recognizes emails as a method for notification, even if you prompt it saying not an email, but a bell notification, it still calls the email sendMessage methods.   (sorry, no access to my prompt I used exactly atm, was in office)

**Comment by jonifazo** [comment]
Hi [A2152225](https://github.com/A2152225)! Thanks for bringing this to our attention. Were you able to provide feedback on this generated response using the "EinsteinGPT: History & Feedback" panel in the Output Panel? Our model learns through feedback so the Thumbs Up/Thumbs Down will help us improve the responses that you're seeing as well.

**Comment by klewis-sfdc** [comment]
I would also encourage you to leave a detailed comment in the Comment box for that prompt in the History & Feedback panel.  This is the best way for this type of feedback to make its way back to the model.

<img width="1077" alt="2023-09-18_14-47-23" src="https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/46458081/df963b62-b0ad-4e5d-8d72-131311d37815">

Thank you for your feedback @A2152225!
