### ISSUE TITLE
Generated response often creates a new Apex class when I'm already within an Apex file

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/Einstein-GPT-for-Developers#2]
Sometimes when I submit a prompt to generate an Apex method, I still get an Apex class in response. I'm already within an Apex file at this point, so the class declaration is unneccessary. 

Repro Steps:

1. Navigate to an existing Apex class file. Run the command from the Command Palette
2. Input prompt like:
`Write an Apex method to compute the total opportunity value of all the Opportunities within a given Account, considering only the opportunities that are larger than the MINIMUM_OPP_SIZE constant which is declared elsewhere in the class.`

Actual Response:
Contains the class declaration
`public class OpportunityValueCompute { public static Decimal computeOpportunityValue(Account account) {   xxx  }}`

Expected Response:
Should not contain the class declaration

**Comment by gbockus-sf** [comment]
This was largely addressed with the LLM update prior to DF.  Closing for now as resolved, but please reopen if new situations where unexpected class/methods are generated.
