### ISSUE TITLE
Extension does not activate in VS Code

### ISSUE THREAD

**Issue by bbarlow-knauf** [forcedotcom/Einstein-GPT-for-Developers#20]
I’ve installed the extension in VS Code, but it has not activated yet as I do not see the Einstein icon in the side bar. I have enable “Einstein for Developers” in the sandbox I am connected to in my sandbox org. I am using the latest version of VS Code 1.82.1 and have the latest version of the SF CLI installed as well. The other SF extensions load just fine.

**Comment by leefranke** [comment]
Same exact issue. I have a feeling that there will be a lot of folks trying this out today as Dreamforce has ended.

**Comment by gbockus-sf** [comment]
Howdy!  
A few questions to help us track down why the extension isn't activating. 
- If you run in the command pallet `Developer: Show Running Extensions` do you see the Einstein for Developers extension listed? 
<img width="1262" alt="Screenshot 2023-09-15 at 10 05 10 AM" src="https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/76090802/36c67130-36e9-4b4a-8f3b-2c0fa55b5a20">

- Do you see the small Einstein icon in the lower right  of the status bar? 
<img width="497" alt="image" src="https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/76090802/a882b713-6adb-42c1-94b9-46b25556dcf3">

We've added the ability to see debug logging.  If you open the settings you can turn on the debug logging with the following setting
<img width="1237" alt="image" src="https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/76090802/ffb5c666-c77c-4c35-930e-29a62117c89a">

After that reload VSCode and open the Developer tools with `Developer: Toggle Developer Tools`. If you right click the console from there you can save the log file.  Please email it to gbockus@salesforce.com.

**Comment by leefranke** [comment]
It seems to be stuck in 'Activating'. 

I do not see that small Einstein icon in the bottom right.
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/55451169/e8a93b73-ca9a-4f45-9bdf-8a230c36a971)

I'll work on getting the debug log to export.

**Comment by gbockus-sf** [comment]
Thanks for the Log @leefranke.  I can see where the Einstein extension is failing to activate b/c it can't find a dependency from the Salesforce CLI Integration extension.  Can you verify what version of the CLI extension you have currently installed? (The latest is v58.14.2).  You will find the extension version in both the Running extensions view and if you find the extension in the extensions panel.

**Comment by leefranke** [comment]
I'm running 57.15.0. I'll update and see if that works.

**Comment by leefranke** [comment]
That sort of worked. It is now running but it threw and error (at least I think it is that extension throwing the error):

Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

I'll send the logs.

**Comment by gbockus-sf** [comment]
Nice.  I created a ticket to detect the version of the CLI extension and provide guidance at activation.  I did a quick google on the webview error and it seems to be an inconsistent VSCode issue.  https://github.com/microsoft/vscode/issues/128649. Can you try a restart and see if it goes away?

**Comment by gbockus-sf** [comment]
@bbarlow-knauf can you check the version of the CLI extension you have installed when you get a few?   I just want to verify it was the same issue Lee was seeing.

**Comment by leefranke** [comment]
The icons appear but the Einstein Sidebar does not have the prompt. I can start a different post for that issue.

**Comment by bbarlow-knauf** [comment]
@gbockus-sf I had an older version of the Salesforce Extension Pack. I updated all of the installed extensions and now Einstein for Developers is working for me. Thanks for the troubleshooting steps!

**Comment by gbockus-sf** [comment]
Closing this one as we found the issue 👍

**Comment by snugsfbay** [comment]
@gbockus-sf my CLI version is "cliVersion": "@salesforce/cli/2.8.11", how are you getting v58.14.2 for CLI? I'm using `sfdx version`
