### ISSUE TITLE
Extension Readme: Add link to docs and screenshot(s)

### ISSUE THREAD

**Issue by thedanfernandez** [forcedotcom/Einstein-GPT-for-Developers#25]
## Issue
Einstein for Developers requires setup instructions that, if you discover the extension, you wouldn't know are required to use the extension. 

## Proposed Fix
Update the extension `README.md`, after the `Overview` section with markdown similar to the following:

```markdown
## Documentation
Please visit the [Einstein for Developers (Beta) documentation](https://developer.salesforce.com/tools/vscode/en/einstein/einstein-overview) for [setup instructions](https://developer.salesforce.com/tools/vscode/en/einstein/einstein-setup)

## Screenshot

![Screenshot of Einstein for Developers generating Apex based on natural language](https://d33wubrfki0l68.cloudfront.net/4b089c34b9e2d170c8ae4dc38c00cf82f47660ef/abad5/images/einstein-sidebar.png)
```

## Documentation

Please visit the [Einstein for Developers (Beta) documentation](https://developer.salesforce.com/tools/vscode/en/einstein/einstein-overview) for [setup instructions](https://developer.salesforce.com/tools/vscode/en/einstein/einstein-setup).

## Screenshot

![Screenshot of Einstein for Developers generating Apex based on natural language](https://d33wubrfki0l68.cloudfront.net/4b089c34b9e2d170c8ae4dc38c00cf82f47660ef/abad5/images/einstein-sidebar.png)

**Comment by gbockus-sf** [comment]
@sbudhirajadoc @AnanyaJha an issue for your consideration
