### ISSUE TITLE
Feedback regarding keyboard Shortcuts

### ISSUE THREAD

**Issue by tahabasri** [forcedotcom/Einstein-GPT-for-Developers#27]
> Originally posted in [salesforcedx-vscode-einstein-gpt](https://github.com/forcedotcom/salesforcedx-vscode-einstein-gpt/issues/149).

The default provided shortcuts of the extension are overriding some of the most important system shortcuts in VSCode, specially for Mac users. I think this issue can be discussed/resolved as the list of shortcuts is still small and maintainable.

### How to reproduce ? MacOS only

- Install Einstein for Developers extension
- Open a repo and connect to a Dev org in which `Einstein for Developers` is enabled
- Open a random Apex class in VSCode in the open repo
- Put the cursor in the middle of a code line, like below:
![image](https://github.com/forcedotcom/salesforcedx-vscode-einstein-gpt/assets/12661966/7d6b7e9c-ded4-46c4-96f1-505572fe4827)

- Hit the combo `cmd+right` in order to go to end of line (default VSCode shortcut)

### Expected ?
Cursor should go to end of line

### Current behavior
Cursor is stuck on the initial position.

### Why ?
The `accept` command trigger (cmd+right) overrides the System shortcut `cursorEnd`, the latter is the commonly used within VSCode. User must either change system settings after installing the extension which is not ideal (given that this change applies to Apex files only).

![image](https://github.com/forcedotcom/salesforcedx-vscode-einstein-gpt/assets/12661966/c38c4a54-3dd5-4d1d-b816-39a2f0b35a83)

Another useful shortcut that's impacted is the famous `cmd+r` which is now triggering `Einstein: Generate Code` instead of reloading VSCode by default.

![image](https://github.com/forcedotcom/salesforcedx-vscode-einstein-gpt/assets/12661966/9c047068-4d6b-45e8-964c-e6590a26655c)

### Suggestions ?
My suggestion is to go with `cmd+shift+key` as this applies for a small set of File types (Apex for now), the learning curve is not much impacted as the keyset is still small. I'm open for any other type of suggestions. Thanks.

**Comment by tahabasri** [comment]
As I can't push code to the original repo, here are my suggested changes:
![image](https://github.com/forcedotcom/salesforcedx-vscode-einstein-gpt/assets/12661966/d15f5297-8746-442c-a9e3-7777821ded6c)

**Comment by floralan** [comment]
Hi @tahabasri, our team is aware of this issue. We have created an internal work item (W-14194362) to fix it. Thank you for your input!

**Comment by d-gunawan** [comment]
@tahabasri, we changed our default keybindings for `acceptSuggestion` and `promptForQuery` in version `0.23.1` so they should no longer conflict with the system keybindings, more details can be found in our [release notes](https://github.com/forcedotcom/Einstein-GPT-for-Developers/releases/tag/v0.23.1). 

The `insertCommentForCodeGeneration` feature is still behind a feature flag, so it shouldn't cause any keybinding conflict.

**Comment by tahabasri** [comment]
Great ! Thanks @d-gunawan  !
