### ISSUE TITLE
Overrides keyboard shortcut on mac

### ISSUE THREAD

**Issue by iamarindamkundu** [forcedotcom/Einstein-GPT-for-Developers#29]
I installed and enabled Einstein for Developer on my sandbox org, after which I notices that on mac `command + right arrow` shortcut to move the cursor to the end of the line is not working. Though, `command + lift arrow` to move the cursor to the beginning is working.
I have tried below options thinking it will fix this issue, however, it didn't fix.

1. Reloaded the vscode after installing the extension
2. Uninstalled and reinstalled the extension

Thanks!

**Comment by jonifazo** [comment]
Hi @iamarindamkundu, our team is aware of this issue. We have created an internal work item (W-14194362) to fix it. Thank you for your input!

**Comment by d-gunawan** [comment]
@iamarindamkundu, we changed some of our default keybindings in version `0.23.1`, more details can be found in our [release notes](https://github.com/forcedotcom/Einstein-GPT-for-Developers/releases/tag/v0.23.1). You should be able to use the `cmd + right arrow` shortcut to move the cursor to the end of the line now with our latest version.
