### ISSUE TITLE
How Einstein for Developer is better than ChatGPT?

### ISSUE THREAD

**Issue by arshadshaikhsajid** [forcedotcom/Einstein-GPT-for-Developers#30]
As ChatGPT also provides more helpful responses and assistant. so what are the different things we can experience here? which features are better thant ChatGPT?can you please give me deep information regarding this?

**Comment by AnanyaJha** [comment]
Hi @arshadshaikhsajid ! Thanks for reaching out - Einstein for Developers is built on Salesforce's internal LLM, CodeGen. This model has been trained on enterprise level Apex code so we aim to provide high-level Apex code that respects known Salesforce best practices. Now, we are just getting started with the Open Beta experience so it's currently limited to Natural Language to Code Generation. We'll be releasing features including Inline Code Completion and Test Case Generation in the upcoming months, with more planned for next year. With this product, our goal is to ensure that we're helping users kickstart their Salesforce development with high-quality Apex code in a toolset that is tightly integrated with our Salesforce Developer ecosystem. If you have existing pain points or feedback on Salesforce Development, we'd love to hear them as we continue to refine our roadmap for next year. Thanks!
