### ISSUE TITLE
SFApiRequestError: Request failed with status code 400

### ISSUE THREAD

**Issue by kamalrao49** [forcedotcom/Einstein-GPT-for-Developers#35]
Getting below error 
SFApiRequestError: Request failed with status code 400

**Comment by SuzanneSG** [comment]
Getting the same error. In VSCode for Windows AND in Code Builder.

**Comment by ranjeet9891** [comment]
Is there any update on the issue. i am also getting the same error message

**Comment by eltoroit** [comment]
The latest version is broken, but I have tested 0.27.1 and that works.

**Comment by kevinmcphail** [comment]
@Andres, .29 also seems to be working.

**Comment by eltoroit** [comment]
I only tested 0.27.1 because that was working before... :-)

**Comment by rajnimtr** [comment]
Facing the same issue. Do we need to install a different version? The 0.29.0 one?

**Comment by eltoroit** [comment]
Try 0.31.0, it's working again.

**Comment by randi274** [comment]
Hey all - is anyone still receiving this message? It looks like our last update was that this was resolved with version 0.31.0, and our latest version is now 0.36.0.

**Comment by BhavsarShivam** [comment]
This is is still faced in 0.31

**Comment by randi274** [comment]
@BhavsarShivam can you try updating to 0.36.0 and let us know if you still have this issue?

**Comment by randi274** [comment]
Closing this issue as we haven't seen it for a while. If anyone else encounters a 400 feel free to comment here, or open a new issue with us!

**Comment by imaginationac** [comment]
Hi. Hit this error with v. 0.40.0
