### ISSUE TITLE
Problem loading Einstein in VScode

### ISSUE THREAD

**Issue by yasselin** [forcedotcom/Einstein-GPT-for-Developers#37]
This is the first message I get

"Looks like you don't have the right permissions to use Einstein for Developers. Your Salesforce admin can help with that by following the steps in the Einstein for Developers page in your org Setup."

and then I get this message when that one goes away
"No Einstein for Developers permission in default org"

**Comment by smarvez** [comment]
Hi @yasselin, please refer to our documentation on how to enable Einstein for Developers in your org: [https://developer.salesforce.com/tools/vscode/en/einstein/einstein-setup](https://developer.salesforce.com/tools/vscode/en/einstein/einstein-setup)
