### ISSUE TITLE
SFAPIRequestError Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by jarlabsh** [forcedotcom/Einstein-GPT-for-Developers#40]
### Summary

SFAPIRequestError Cannot set headers after they are sent to the client
### Steps To Reproduce:

1.  When trying any prompt

### Expected result

Get answers

### Actual result

Error prompt appears

### Additional information

**Salesforce Extension Version in VS Code**: Latest

**Salesforce Einstein For Developers Version in VS Code**: Latest

**OS and version**: Windows 11

**VS Code version**: 1.80

**Comment by randi274** [comment]
Hey @jarlabsh could you send us a screenshot or a video of what's happening when you encounter this error? If you Toggle the Developer Tools, do you see any additional error details?

**Comment by randi274** [comment]
Closing this issue as we haven't seen it for a while. If anyone else encounters this error again feel free to comment here, or open a new issue with us!
