### ISSUE TITLE
Einstein for Developer keeps on Activating and never gets Activated

### ISSUE THREAD

**Issue by debprotim** [forcedotcom/Einstein-GPT-for-Developers#49]
### Summary

I updated my VSCode and CLI to the latest version on ask of Salesforce Support. But now Einstein for Developer extension is STUCK at Activating...

### Steps To Reproduce:

1.  Update VSCode to latest version 1.86.1
2. Update Salesforce CLI Extension to latest version v60.2.3
3. Run Developer: Show Running Extensions
4. You can find the extension stuck at Activating

### Expected result

Einstein icon to showup on the taskbar and on the left panel

### Actual result

No icon available

### Additional information

![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/8632083/3b6cb02e-a5a3-49f1-8352-988a926819c7)

**Salesforce Extension Version in VS Code**: v60.2.3

**Salesforce Einstein For Developers Version in VS Code**: v0.39.0

**OS and version**: Windows

**VS Code version**: 1.86.1

**Comment by AnanyaJha** [comment]
Hi @debprotim - sorry you're seeing these issues! We'll have a member of our team investigate cc @randi274

**Comment by randi274** [comment]
For others who may run into this issue as well - ensure that the "Salesforce CLI Integration" extension and the "Apex" extension are both active, as they are both dependencies of this extension. To confirm this, run a command such as `SFDX: Refresh SObject Definitions` and `SFDX: Run Apex Tests`.

**Comment by debprotim** [comment]
Please close this request, finally it has started activating. The moment i fixed my CLI issue, it got automatically fixed. I created a new request for the another issue I am facing #60

**Comment by randi274** [comment]
That's great progress @debprotim! Thanks for sticking it out with the setup on this. We'll focus our troubleshooting efforts on the other issue/case.
