### ISSUE TITLE
Einstein For developers suggesting System.assert instead of Assert class

### ISSUE THREAD

**Issue by salikbhatti** [forcedotcom/Einstein-GPT-for-Developers#56]
### Summary

When generating test classes Einstein for developers is using system.assert instead of the Assert class that was made available in October 2022, 

Is einstein for developers not being trained on latest Apex methods & classes, is there a way to know how old data it has been trained on

**Comment by lahernandezb** [comment]
Thanks for reporting this issue! We’re aware of this issue and we’ll be working closely with our AI Research team to ensure that responses are following most recent best practices.
