### ISSUE TITLE
SFApiRequestError: Request failed with status code 500

### ISSUE THREAD

**Issue by elliot41** [forcedotcom/Einstein-GPT-for-Developers#58]
### Summary

Hi developer team, 

I want to use the extension behind a company proxy, though, when I click the button "Ask" I have the error message (SFApiRequestError: Request failed with status code 500). Can you tell me what is the url called ? In order to allow it in the proxy ?

**Comment by jonifazo** [comment]
Hello! The URLs accessed by the extension are:

- https://api.salesforce.com/einstein/gpt/code/v1-alpha.1/generations
- https://api.salesforce.com/einstein/gpt/code/v1-alpha.1/feedback

**Comment by elliot41** [comment]
Hi @jonifazo,

I whitlisted the host : https://api.salesforce.com/

However I still have the same error. Is there other endpoints that I should whitelist ?

**Comment by jonifazo** [comment]
Hi @elliot41 - I missed your message last week. Apologies for the delay! Were you able to solve your issue?

Best,
Joni

**Comment by gbockus-sf** [comment]
Hi @elliot41 
I'm going to close this issue out as we haven't heard back in a while.  If you are still seeing proxy issue please see my comment on https://github.com/forcedotcom/Einstein-GPT-for-Developers/issues/60.  As always feel free to reopen if we can be of assistance.
