### ISSUE TITLE
Conversational Agent Trained on all Salesforce Documentation.

### ISSUE THREAD

**Issue by jonnyhork** [forcedotcom/Einstein-GPT-for-Developers#64]
**Is your feature request related to a problem? Please describe.**

While it is nice to have some help when it comes to refactoring my code or getting started with some tests, I find that most of the time I really just need help understanding or finding the information I need in the documentation. For example, I may not know what a specific XML tag in the metadata does, what the possible values could be and why I might care about it.

A lot of my work as a developer is about finding and understanding the answers I need in documentation before I get to implementation (code).

**Describe the solution you'd like**

I want to be able to ask Einstein questions about to developing on the platform that are not specific to code. I would love to highlight some method attributes in APEX and have it explain what it does and link to some docs, or ask "How do I make my custom object only accessible to the current user?", I want Einstein to help understand the "why" not just the "what" (code).

I want Einstein exceptionally and specifically knowledgeable about everything technical at Salesforce, everything in [developers.salesforce.com](https://developer.salesforce.com/)

**Describe alternatives you've considered**

I'll use 3rd party extensions that provide access to Chat GPT in VS Code

**Additional context**
<img width="1049" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/25188632/0a639e76-0c18-4ed0-8c7c-8f134e63dacc">

**Comment by floralan** [comment]
@jonnyhork Hi Jonny, thank you for your feedback! You've highlighted some excellent use cases for the new chat experience we're developing. Our team is currently building a new E4D chat that can handle broader questions like those you mentioned. We'll be using a new LLM - XGen, which will enable it to not only generate code but also answer more general questions. Stay tuned for updates!

**Comment by jonnyhork** [comment]
Awesome, looking forward to it!
