### ISSUE TITLE
No option to enable Einstein for Developers even after creating a new dev sandbox.

### ISSUE THREAD

**Issue by brycekilker** [forcedotcom/Einstein-GPT-for-Developers#69]
### Summary

I have never gotten Einstein for Developers to work in our org. I have VS Code and the extensions up to date. Following the documentation I created a new sandbox, but still do not have the option to authorize Einstein for Developers. When I search this in Prod, I see Einstein for Developers, but the screen does not have a toggle to activate or any other interactable UI.

### Steps To Reproduce:

1.  When I search 'Einstein for Developers' in my Developer org's quick find box, nothing is found.
2.  Status in VSCode: Status: No Einstein for Developers found in Default Org.

**Salesforce Extension Version in VS Code**: Salesforce Extension Pack
v60.11.0

**Salesforce Einstein For Developers Version in VS Code**: Einstein for Developers (Beta)
v0.45.1

**OS and version**: Windows 11 23H2

**VS Code version**: version 1.89

**Comment by jonifazo** [comment]
Hi @brycekilker - Thank you for reaching out. Could you please share your orgId(s)?
Best,
Joni

**Comment by brycekilker** [comment]
Thanks, the dev org is 00DVZ000000O28j and our prod ID is 00D1U000000tRDL

**Comment by jonifazo** [comment]
Thanks @brycekilker. I will look into this today!

**Comment by jonifazo** [comment]
Hi @brycekilker - Could you please let me know what instance your orgs are on? Here's how you get that info: Setup > Company Settings section > Company Information page > Organization Detail section > Instance field

**Comment by brycekilker** [comment]
@jonifazo Prod is USA418 and our Sandbox is USA752S

**Comment by jonifazo** [comment]
Hi @brycekilker - 
A couple follow up questions...
1. Can you confirm that when your org is in Lighting Experience you do not see "Einstein for Developers" in Setup?
2. From your VSCode command palette, do you see the command "SFDX: Deploy This Source to Org"?

Thanks,
Joni

**Comment by brycekilker** [comment]
1. In Sandbox, (first screenshot) nothing comes up when I search 'Einstein for Developers', in prod, something does come up, but there is no ui on the page to toggle anything on.
2. Yes, I have all of the Salesforce CLI commands in VSCode.
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/43078192/c77b2707-6d7b-48db-966e-26bccbc587b1)
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/43078192/0f708285-0b70-4d69-8f59-d3cbeacb1790)

**Comment by jonifazo** [comment]
Hi @brycekilker - I'm having trouble tracking down logs for your orgs. When you have time, could you please try using E4D in both of your orgs and send me screenshots of the errors you encounter? I can then try again to correlate your errors with our logging.
Thanks,
Joni

**Comment by brycekilker** [comment]
@jonifazo Alright, that is interesting. When I authorized my production org, it actually worked, but I obviously do not want to write code in production. Interesting that it worked there and not sandbox.
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/43078192/62d9dab3-7d04-4af9-9e3e-776ae899e0ed)
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/43078192/dd0251dd-b155-4bdd-872c-1f3a8ce98c19)

**Comment by jonifazo** [comment]
Hi @brycekilker - 

I have confirmed that your sandbox org does not have the correct perms and it should. 

Could you please file a support case using https://help.salesforce.com/s/support and then let me know the case #? This will allow me to follow up with someone that is (hopefully) able to grant your sandbox org the correct perms and also give us insight into whether this issue is impacting others.

Thank you so much for taking the time to reach out on this! 

Best,
Joni

**Comment by brycekilker** [comment]
Thank you @jonifazo I actually had a case open for this sometime ago, but was not adequately assisted. Here's the case number if you are able to reopen it and maybe find a better solution. Let me know if you would like me to open a new case instead.
Case #40394249-SF

**Comment by jonifazo** [comment]
Thanks @brycekilker. I appreciate your patience on this. I will look into this further today.

**Comment by jonifazo** [comment]
Hi @brycekilker - Unfortunately since the case is older than 10 days I am unable to have it reopened. Could you please start a new case and share the case # here so I may investigate further with a support engineer?

**Comment by brycekilker** [comment]
Salesforce Support was able to solve this. I matched the license in my sandbox with production following the below steps. Thank you for your help.

Go to Sandbox --> Setup--> Company Settings | Company Information | Match Production Licenses.
