### ISSUE TITLE
Known Issue: Inline Code Completions showing intermittently

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/Einstein-GPT-for-Developers#76]
There is a known issue where Inline Code Completion will show completions intermittently. This is an active issue that the team is closely monitoring, we'll be sharing updates on this thread as we have them. 

In the meantime, we recommend retrying your completion request after a few minutes with the (OPT/Alt + SLASH) keyboard shortcut. Let us know if you're seeing any issues or have feedback!

**Comment by gbockus-sf** [comment]
Service issues have been addressed (as of last week) .
