### ISSUE TITLE
Einstein developer not generating appropriate test classes

### ISSUE THREAD

**Issue by vermaamit796** [forcedotcom/Einstein-GPT-for-Developers#77]
When try to generate the test class for any apex class, Einstein developer not able to generate the correct test classes. Some of the issues observed:-
1. Test class generated not calling to the correct apex class for code coverage
2. Not cover all the scenarios of the classes

**Comment by randi274** [comment]
Hi @vermaamit796 - thanks for the feebdack! Is this happening with the use of our Test Case Generation [Feature](https://developer.salesforce.com/tools/vscode/en/einstein/einstein-testcasegen)?

Can you provide some examples for what you're seeing with the generations being incorrect? We can use examples to reproduce your findings and pass that to our internal teams to improve our generation quality

**Comment by gbockus-sf** [comment]
Closing this as there hasn't been any action for over a month.  Please reopen if you'd like to re-engage.  Thanks!
