### ISSUE TITLE
Trigger Inline Suggestion not available on VS Code

### ISSUE THREAD

**Issue by albarivas** [forcedotcom/Einstein-GPT-for-Developers#78]
### Summary

When I open the shortcuts menu, "Trigger Inline Suggestion" is not there, and thus I cannot assign a shortcut to it. This is happening only on VS Code (works in Code Builder). 

### Steps To Reproduce:

1.  Open shortcuts for E4D
2.  Look for "Trigger Inline Suggestion"

### Expected result
It should be there

### Actual result
It's not there

### Additional information

![Screenshot 2024-06-26 at 08 48 07](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/12017842/ff457707-c3e0-45b2-acd3-8f618fba6a78)

**Salesforce Extension Version in VS Code**: 61.1.2

**Salesforce Einstein For Developers Version in VS Code**: 0.50.0

**OS and version**: Sonoma 14.5

**VS Code version**: 1.90.0

**Comment by smarvez** [comment]
Hi @albarivas - searching by Einstein for Developers I'm able to see it. Can you please check again and let me know if you're able to find it? 
![Screenshot 2024-07-01 at 3 15 42 PM](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/30200040/3034d034-474a-439b-b0f2-1d915d723181)

**Comment by albarivas** [comment]
I am not, but I am in touch with an engineer for the product, I'll post the solution here if we find it

**Comment by smarvez** [comment]
Hi again @albarivas, I saw that Gordon suggested manually assigning a shortcut to the Trigger Inline Completion command. Did that resolve the issue for you?

**Comment by albarivas** [comment]
Yes - that worked. It was weird that the command was unlinked by default, and did not appear under Einstein for Developers commands, but it was actually there (found it in the regular commands view) and assigning a shortcut to it did the trick. Thanks for your help!
