### ISSUE TITLE
SFApiRequestError: Request failed with status code 401

### ISSUE THREAD

**Issue by sanaullah-sayedSFDC** [forcedotcom/Einstein-GPT-for-Developers#81]
### Getting this error when trying anything in Einstein sidebar.: SFApiRequestError: Request failed with status code 401

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Enable Einstein for developer
2.  Give any prompt in Einstein Sidebar.

### Expected result : code 

_Describe what should have happened_.

### SFApiRequestError: Request failed with status code 401

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**Salesforce Einstein For Developers Version in VS Code**:

**OS and version**:

**VS Code version**:

**Comment by jonifazo** [comment]
Hi @sanaullah-sayedSFDC - 

We had an issue with service last week but it should be resolved now. Are you still experiencing this error?
