### ISSUE TITLE
History when generating tests included an "undefined" in every row

### ISSUE THREAD

**Issue by albarivas** [forcedotcom/Einstein-GPT-for-Developers#84]
### Summary

History when generating tests included an "undefined" in every row
### Steps To Reproduce:

1.  Activate logging
2. Generate a test
3. Go to history tab

### Expected result

No undefined should be shown.

### Actual result

![Screenshot 2024-07-05 at 13 17 22](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/12017842/1a4ec654-255e-46e5-a482-f5a966db18cb)

### Additional information
Salesforce Extension Version in Code builder: 61.1.2

Salesforce Einstein For Developers Version in Code builder: 0.50.0

code-server: v4.18.0

Code: 1.83.1

**Comment by jonifazo** [comment]
Hi @albarivas - Thanks for bringing this to our attention! I will investigate and let you know what I learn.
Best,
Joni

**Comment by jonifazo** [comment]
Hi @albarivas - Thanks again for bringing this to our attention. I have created a bug for this issue: [W-16189729](https://gus.lightning.force.com/a07EE00001wDfOsYAK)

**Comment by gbockus-sf** [comment]
@albarivas I think this might has been an issue with older version of E4D, but I am no longer able to repo. I tested with the latest CB build and did not encounter the missing label.  Please repo if you are still seeing the issue.
