### ISSUE TITLE
Einstein Status: Not Connected To Default Org (Default org is connected) - Codebuilder

### ISSUE THREAD

**Issue by aidanfowler** [forcedotcom/Einstein-GPT-for-Developers#90]
### Summary

I cannot complete activation of Einstein For Developers, the status always shows not connected to default org. Default org is connected - confirmed by sf org list shows org with status = Connected and leaf next to org designating it as the default. 

### Steps To Reproduce:

1. SFDX: Authorize Org, default, alias = staging, flow works as expected, I can pull metadata into codebuilder
2. Einstein for developers icon is continuous loading spinner, if you click on it it says Status: Not Connected To Default Org

### Expected result

Should be connected as appears on command line. 

### Additional information

_Feel free to attach a screenshot_.
<img width="881" alt="Screenshot 2024-09-03 at 1 58 49 PM" src="https://github.com/user-attachments/assets/d31f903d-30e1-47c7-8ba8-c4d832e8f209">

**Salesforce Extension Version in VS Code**:
v61.11.0

**Salesforce Einstein For Developers Version in VS Code**:
v0.60.0

**OS and version**:
Mac OS Sonoma 14.6

**VS Code version**:
Using codebuilder

**Comment by gbockus-sf** [comment]
Hi @aidanfowler 
Sorry for the slow response it's been an insane run up to Dreamforce.  This sounds like an known issue that has surfaced around using the device auth flow.  Can you try Auth'ing your Codebuilder org using the workaround document in https://github.com/forcedotcom/Einstein-GPT-for-Developers/issues/93? 
Thanks

**Comment by gbockus-sf** [comment]
Closing as there is a known issue with device auth on CB being tracked in #93.  Please reopen if the workaround there does not address your issue. 
Thanks!
