### ISSUE TITLE
Einstein for Developer  Extension not working in my VS COde

### ISSUE THREAD

**Issue by VipinSingh9680** [forcedotcom/Einstein-GPT-for-Developers#92]
Hi, I have installed Einstein for Developer Extension and my vs code is also have latest version , but it's now working as expected , Einstein Dev Assistant , also not generating any code it throwing an issue when I am searching any solution

**Comment by D41283613** [comment]
Im also facing the same issue

**Comment by gbockus-sf** [comment]
Hi @VipinSingh9680 @D41283613 Can you provide more details about how it is not working?  Is is just an empty response in the chat panel when you submit a question?   We had a few issues we are fixing in the next release where this situation will occur, but if you clear the chat it should reset and you'd be back in business.

**Comment by VipinSingh9680** [comment]
Hi,
Yes it is just simply coming empty or sometime it's showing thinking
(Loading) only, and also inline editor suggestion is not working for my
Apex code, but it's working for my LWC

**Comment by gbockus-sf** [comment]
Gotcha! Thanks for the feedback.  We have a release coming in the next day or two that fix that bug.  Will keep this issue open until we get that release out.

**Comment by gbockus-sf** [comment]
Fix has been released with v0.61.0.  Closing as the issue should be resolved.  Please reopen if that's not the case. 

Thanks!
